# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1240, 878)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.verticalWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.verticalWidget.setBaseSize(QtCore.QSize(300, 0))
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelvreme = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelvreme.sizePolicy().hasHeightForWidth())
        self.labelvreme.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelvreme.setFont(font)
        self.labelvreme.setAlignment(QtCore.Qt.AlignCenter)
        self.labelvreme.setObjectName(_fromUtf8("labelvreme"))
        self.verticalLayout_4.addWidget(self.labelvreme)
        self.labeldatum = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labeldatum.sizePolicy().hasHeightForWidth())
        self.labeldatum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labeldatum.setFont(font)
        self.labeldatum.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldatum.setObjectName(_fromUtf8("labeldatum"))
        self.verticalLayout_4.addWidget(self.labeldatum)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_2.setPalette(palette)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.imerecepture = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imerecepture.sizePolicy().hasHeightForWidth())
        self.imerecepture.setSizePolicy(sizePolicy)
        self.imerecepture.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imerecepture.setObjectName(_fromUtf8("imerecepture"))
        self.verticalLayout_5.addWidget(self.imerecepture)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.brojodvagauz = QtGui.QLineEdit(self.groupBox_2)
        self.brojodvagauz.setObjectName(_fromUtf8("brojodvagauz"))
        self.horizontalLayout_4.addWidget(self.brojodvagauz)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.trenutnibinzasipanje = QtGui.QLabel(self.groupBox_2)
        self.trenutnibinzasipanje.setObjectName(_fromUtf8("trenutnibinzasipanje"))
        self.horizontalLayout_9.addWidget(self.trenutnibinzasipanje)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.kolicinazavaganje = QtGui.QLabel(self.groupBox_2)
        self.kolicinazavaganje.setObjectName(_fromUtf8("kolicinazavaganje"))
        self.horizontalLayout_8.addWidget(self.kolicinazavaganje)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.brojtrenutneodvage = QtGui.QLabel(self.groupBox_2)
        self.brojtrenutneodvage.setObjectName(_fromUtf8("brojtrenutneodvage"))
        self.horizontalLayout_7.addWidget(self.brojtrenutneodvage)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_7.addWidget(self.lineEdit_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.krajnjavrednostodvage = QtGui.QLabel(self.groupBox_2)
        self.krajnjavrednostodvage.setObjectName(_fromUtf8("krajnjavrednostodvage"))
        self.horizontalLayout_6.addWidget(self.krajnjavrednostodvage)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.pushButton = QtGui.QPushButton(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.tableWidget = QtGui.QTableWidget(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = GlavniProzor()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 950, 514))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(950, 460))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 228, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 228, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 228, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 228, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollAreaWidgetContents.setPalette(palette)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 170, 151, 71))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setContentsMargins(-1, 5, 20, 5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.vagamera_2 = QtGui.QTextEdit(self.groupBox_5)
        self.vagamera_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.vagamera_2.setFont(font)
        self.vagamera_2.setUndoRedoEnabled(False)
        self.vagamera_2.setReadOnly(True)
        self.vagamera_2.setAcceptRichText(False)
        self.vagamera_2.setObjectName(_fromUtf8("vagamera_2"))
        self.verticalLayout_9.addWidget(self.vagamera_2)
        self.vaga2edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.vaga2edit.setGeometry(QtCore.QRect(250, 220, 71, 20))
        self.vaga2edit.setReadOnly(True)
        self.vaga2edit.setObjectName(_fromUtf8("vaga2edit"))
        self.lineEdit_13 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_13.setGeometry(QtCore.QRect(250, 360, 61, 20))
        self.lineEdit_13.setReadOnly(False)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.checkBox_6 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_6.setGeometry(QtCore.QRect(230, 410, 141, 17))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setGeometry(QtCore.QRect(760, 160, 171, 271))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.verticalLayout_10.addWidget(self.radioButton_8)
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.verticalLayout_10.addWidget(self.radioButton_9)
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.verticalLayout_10.addWidget(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.verticalLayout_10.addWidget(self.radioButton_11)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.verticalLayout_10.addWidget(self.radioButton_12)
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.verticalLayout_10.addWidget(self.radioButton_13)
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.verticalLayout_10.addWidget(self.radioButton_14)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(550, 220, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.lineEdit_15 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_15.setGeometry(QtCore.QRect(450, 270, 161, 20))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_14.setGeometry(QtCore.QRect(550, 310, 61, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.dugmestopele = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.dugmestopele.setGeometry(QtCore.QRect(600, 370, 75, 23))
        self.dugmestopele.setObjectName(_fromUtf8("dugmestopele"))
        self.verticalLayoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 270, 160, 51))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.checkBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_11.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_11.addWidget(self.checkBox_5)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(10, 10, 921, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_bin1 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin1.setFont(font)
        self.label_bin1.setObjectName(_fromUtf8("label_bin1"))
        self.horizontalLayout_2.addWidget(self.label_bin1)
        self.label_bin2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin2.setFont(font)
        self.label_bin2.setObjectName(_fromUtf8("label_bin2"))
        self.horizontalLayout_2.addWidget(self.label_bin2)
        self.label_bin3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin3.setFont(font)
        self.label_bin3.setObjectName(_fromUtf8("label_bin3"))
        self.horizontalLayout_2.addWidget(self.label_bin3)
        self.label_bin4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin4.setFont(font)
        self.label_bin4.setObjectName(_fromUtf8("label_bin4"))
        self.horizontalLayout_2.addWidget(self.label_bin4)
        self.label_bin5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin5.setFont(font)
        self.label_bin5.setObjectName(_fromUtf8("label_bin5"))
        self.horizontalLayout_2.addWidget(self.label_bin5)
        self.label_bin6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin6.setFont(font)
        self.label_bin6.setObjectName(_fromUtf8("label_bin6"))
        self.horizontalLayout_2.addWidget(self.label_bin6)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.widget_5 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setGeometry(QtCore.QRect(10, 120, 921, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 212, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_5.setPalette(palette)
        self.widget_5.setAutoFillBackground(True)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.label_bin7 = QtGui.QLabel(self.widget_5)
        self.label_bin7.setGeometry(QtCore.QRect(50, 10, 82, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin7.setFont(font)
        self.label_bin7.setObjectName(_fromUtf8("label_bin7"))
        self.label_bin8 = QtGui.QLabel(self.widget_5)
        self.label_bin8.setGeometry(QtCore.QRect(200, 10, 82, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin8.setFont(font)
        self.label_bin8.setObjectName(_fromUtf8("label_bin8"))
        self.label_bin9 = QtGui.QLabel(self.widget_5)
        self.label_bin9.setGeometry(QtCore.QRect(360, 10, 82, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin9.setFont(font)
        self.label_bin9.setObjectName(_fromUtf8("label_bin9"))
        self.label_bin10 = QtGui.QLabel(self.widget_5)
        self.label_bin10.setGeometry(QtCore.QRect(510, 10, 82, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin10.setFont(font)
        self.label_bin10.setObjectName(_fromUtf8("label_bin10"))
        self.label_bin11 = QtGui.QLabel(self.widget_5)
        self.label_bin11.setGeometry(QtCore.QRect(680, 10, 82, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin11.setFont(font)
        self.label_bin11.setObjectName(_fromUtf8("label_bin11"))
        self.label_bin12 = QtGui.QLabel(self.widget_5)
        self.label_bin12.setGeometry(QtCore.QRect(820, 10, 82, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_bin12.setFont(font)
        self.label_bin12.setObjectName(_fromUtf8("label_bin12"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.statustext = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statustext.sizePolicy().hasHeightForWidth())
        self.statustext.setSizePolicy(sizePolicy)
        self.statustext.setMinimumSize(QtCore.QSize(420, 0))
        self.statustext.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.statustext.setObjectName(_fromUtf8("statustext"))
        self.horizontalLayout_10.addWidget(self.statustext)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.widget_3 = NkGrafik(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(600, 200))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_6.addWidget(self.widget_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_2.setPalette(palette)
        self.widget_2.setAutoFillBackground(True)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.startdugme = QtGui.QPushButton(self.widget_2)
        self.startdugme.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.startdugme.setFont(font)
        self.startdugme.setAutoFillBackground(False)
        self.startdugme.setObjectName(_fromUtf8("startdugme"))
        self.horizontalLayout_11.addWidget(self.startdugme)
        spacerItem2 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.stopdugme = QtGui.QPushButton(self.widget_2)
        self.stopdugme.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stopdugme.setFont(font)
        self.stopdugme.setObjectName(_fromUtf8("stopdugme"))
        self.horizontalLayout_11.addWidget(self.stopdugme)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.widget_4 = QtGui.QWidget(self.centralwidget)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.dugme_krajodvage = QtGui.QPushButton(self.widget_4)
        self.dugme_krajodvage.setObjectName(_fromUtf8("dugme_krajodvage"))
        self.horizontalLayout_12.addWidget(self.dugme_krajodvage)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.dugme_novizadatak = QtGui.QPushButton(self.widget_4)
        self.dugme_novizadatak.setObjectName(_fromUtf8("dugme_novizadatak"))
        self.horizontalLayout_12.addWidget(self.dugme_novizadatak)
        self.dugme_brisizadatak = QtGui.QPushButton(self.widget_4)
        self.dugme_brisizadatak.setObjectName(_fromUtf8("dugme_brisizadatak"))
        self.horizontalLayout_12.addWidget(self.dugme_brisizadatak)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.tableWidget_2 = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPregledi_i_izvestaji = QtGui.QMenu(self.menubar)
        self.menuPregledi_i_izvestaji.setObjectName(_fromUtf8("menuPregledi_i_izvestaji"))
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuPregledi_i_izvestaji.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelvreme.setText(_translate("MainWindow", "vreme", None))
        self.labeldatum.setText(_translate("MainWindow", "datum", None))
        self.label.setText(_translate("MainWindow", "Trenutni zadatak:", None))
        self.label_2.setText(_translate("MainWindow", "Ime recepture:", None))
        self.label_3.setText(_translate("MainWindow", "Broj odvaga u zadatku:", None))
        self.trenutnibinzasipanje.setText(_translate("MainWindow", "Trenutni bin za sipanje:", None))
        self.kolicinazavaganje.setText(_translate("MainWindow", "Kolicina za vaganje komponente:", None))
        self.brojtrenutneodvage.setText(_translate("MainWindow", "Broj trenutne odvage:", None))
        self.krajnjavrednostodvage.setText(_translate("MainWindow", "Krajnja vrednost odvage:", None))
        self.label_8.setText(_translate("MainWindow", "kg", None))
        self.pushButton.setText(_translate("MainWindow", "Isprazni tabelu", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Trenutna merena vrednost", None))
        self.vagamera_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-</p></body></html>", None))
        self.checkBox_6.setText(_translate("MainWindow", "ELEVATOR MLINA", None))
        self.radioButton_8.setText(_translate("MainWindow", "Vaga 1", None))
        self.radioButton_9.setText(_translate("MainWindow", "Vaga 2", None))
        self.radioButton_10.setText(_translate("MainWindow", "Vaga 3", None))
        self.radioButton_11.setText(_translate("MainWindow", "Vaga 4", None))
        self.radioButton_12.setText(_translate("MainWindow", "Peletirka", None))
        self.radioButton_13.setText(_translate("MainWindow", "Ekstruder bin5", None))
        self.radioButton_14.setText(_translate("MainWindow", "Ekstruder bin 6", None))
        self.pushButton_9.setText(_translate("MainWindow", "NAPUNI", None))
        self.lineEdit_15.setText(_translate("MainWindow", "Spremna", None))
        self.dugmestopele.setText(_translate("MainWindow", "STOP", None))
        self.checkBox_4.setText(_translate("MainWindow", "DOTOK MATERIJALA", None))
        self.checkBox_5.setText(_translate("MainWindow", "MLIN", None))
        self.label_bin1.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin2.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin3.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin4.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin5.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin6.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin7.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin8.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin9.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin10.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin11.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_bin12.setText(_translate("MainWindow", "SOJINA POGACA", None))
        self.label_9.setText(_translate("MainWindow", "Status:", None))
        self.startdugme.setText(_translate("MainWindow", "START", None))
        self.stopdugme.setText(_translate("MainWindow", "STOP", None))
        self.label_10.setText(_translate("MainWindow", "Zadaci:", None))
        self.dugme_krajodvage.setText(_translate("MainWindow", "Kraj odvage", None))
        self.dugme_novizadatak.setText(_translate("MainWindow", "Novi zadatak", None))
        self.dugme_brisizadatak.setText(_translate("MainWindow", "Brisi zadatak", None))
        self.menuPregledi_i_izvestaji.setTitle(_translate("MainWindow", "Pregledi i izvestaji", None))

from grafik import NkGrafik
from widgetGlavni import GlavniProzor
