# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rucnewindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1163, 905)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.glavni = QtGui.QWidget(MainWindow)
        self.glavni.setObjectName(_fromUtf8("glavni"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.glavni)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gornji = QtGui.QHBoxLayout()
        self.gornji.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gornji.setObjectName(_fromUtf8("gornji"))
        self.widget = QtGui.QWidget(self.glavni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 201, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 201, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 201, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 201, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gornji_bin1 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin1.setFont(font)
        self.gornji_bin1.setObjectName(_fromUtf8("gornji_bin1"))
        self.verticalLayout_3.addWidget(self.gornji_bin1)
        self.gornji_bin2 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin2.setFont(font)
        self.gornji_bin2.setObjectName(_fromUtf8("gornji_bin2"))
        self.verticalLayout_3.addWidget(self.gornji_bin2)
        self.gornji_bin3 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin3.setFont(font)
        self.gornji_bin3.setObjectName(_fromUtf8("gornji_bin3"))
        self.verticalLayout_3.addWidget(self.gornji_bin3)
        self.gornji_bin4 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin4.setFont(font)
        self.gornji_bin4.setObjectName(_fromUtf8("gornji_bin4"))
        self.verticalLayout_3.addWidget(self.gornji_bin4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.gornji_bin5 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin5.setFont(font)
        self.gornji_bin5.setObjectName(_fromUtf8("gornji_bin5"))
        self.verticalLayout_13.addWidget(self.gornji_bin5)
        self.gornji_bin6 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin6.setFont(font)
        self.gornji_bin6.setObjectName(_fromUtf8("gornji_bin6"))
        self.verticalLayout_13.addWidget(self.gornji_bin6)
        self.gornji_bin7 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin7.setFont(font)
        self.gornji_bin7.setObjectName(_fromUtf8("gornji_bin7"))
        self.verticalLayout_13.addWidget(self.gornji_bin7)
        self.gornji_bin8 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin8.setFont(font)
        self.gornji_bin8.setObjectName(_fromUtf8("gornji_bin8"))
        self.verticalLayout_13.addWidget(self.gornji_bin8)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gornji_bin9 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin9.setFont(font)
        self.gornji_bin9.setObjectName(_fromUtf8("gornji_bin9"))
        self.verticalLayout_14.addWidget(self.gornji_bin9)
        self.gornji_bin12 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_bin12.setFont(font)
        self.gornji_bin12.setObjectName(_fromUtf8("gornji_bin12"))
        self.verticalLayout_14.addWidget(self.gornji_bin12)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gornji_c15 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_c15.setFont(font)
        self.gornji_c15.setObjectName(_fromUtf8("gornji_c15"))
        self.verticalLayout.addWidget(self.gornji_c15)
        self.gornji_c29 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_c29.setFont(font)
        self.gornji_c29.setObjectName(_fromUtf8("gornji_c29"))
        self.verticalLayout.addWidget(self.gornji_c29)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_15.addWidget(self.label)
        self.gornji_22 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_22.setFont(font)
        self.gornji_22.setObjectName(_fromUtf8("gornji_22"))
        self.verticalLayout_15.addWidget(self.gornji_22)
        self.gornji_26 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_26.setFont(font)
        self.gornji_26.setObjectName(_fromUtf8("gornji_26"))
        self.verticalLayout_15.addWidget(self.gornji_26)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_16.addWidget(self.label_2)
        self.gornji_17 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_17.setFont(font)
        self.gornji_17.setObjectName(_fromUtf8("gornji_17"))
        self.verticalLayout_16.addWidget(self.gornji_17)
        self.gornji_16 = idQCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gornji_16.setFont(font)
        self.gornji_16.setObjectName(_fromUtf8("gornji_16"))
        self.verticalLayout_16.addWidget(self.gornji_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gornji.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.gornji)
        self.srednji = QtGui.QHBoxLayout()
        self.srednji.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.srednji.setContentsMargins(-1, -1, 0, -1)
        self.srednji.setObjectName(_fromUtf8("srednji"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_3 = QtGui.QGroupBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setContentsMargins(-1, -1, -1, 2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.srednji_ele2_1 = QtGui.QRadioButton(self.groupBox_3)
        self.srednji_ele2_1.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele2_1.setFont(font)
        self.srednji_ele2_1.setObjectName(_fromUtf8("srednji_ele2_1"))
        self.verticalLayout_9.addWidget(self.srednji_ele2_1)
        self.srednji_ele2_2 = QtGui.QRadioButton(self.groupBox_3)
        self.srednji_ele2_2.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele2_2.setFont(font)
        self.srednji_ele2_2.setObjectName(_fromUtf8("srednji_ele2_2"))
        self.verticalLayout_9.addWidget(self.srednji_ele2_2)
        self.srednji_ele2_3 = QtGui.QRadioButton(self.groupBox_3)
        self.srednji_ele2_3.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele2_3.setFont(font)
        self.srednji_ele2_3.setObjectName(_fromUtf8("srednji_ele2_3"))
        self.verticalLayout_9.addWidget(self.srednji_ele2_3)
        self.srednji_ele2_4 = QtGui.QRadioButton(self.groupBox_3)
        self.srednji_ele2_4.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele2_4.setFont(font)
        self.srednji_ele2_4.setObjectName(_fromUtf8("srednji_ele2_4"))
        self.verticalLayout_9.addWidget(self.srednji_ele2_4)
        self.srednji_ele2_5 = QtGui.QRadioButton(self.groupBox_3)
        self.srednji_ele2_5.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele2_5.setFont(font)
        self.srednji_ele2_5.setObjectName(_fromUtf8("srednji_ele2_5"))
        self.verticalLayout_9.addWidget(self.srednji_ele2_5)
        self.srednji_ele2_6 = QtGui.QRadioButton(self.groupBox_3)
        self.srednji_ele2_6.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele2_6.setFont(font)
        self.srednji_ele2_6.setObjectName(_fromUtf8("srednji_ele2_6"))
        self.verticalLayout_9.addWidget(self.srednji_ele2_6)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.srednji_ispusti_1 = QtGui.QRadioButton(self.groupBox_2)
        self.srednji_ispusti_1.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ispusti_1.setFont(font)
        self.srednji_ispusti_1.setObjectName(_fromUtf8("srednji_ispusti_1"))
        self.verticalLayout_10.addWidget(self.srednji_ispusti_1)
        self.srednji_ispusti_2 = QtGui.QRadioButton(self.groupBox_2)
        self.srednji_ispusti_2.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ispusti_2.setFont(font)
        self.srednji_ispusti_2.setObjectName(_fromUtf8("srednji_ispusti_2"))
        self.verticalLayout_10.addWidget(self.srednji_ispusti_2)
        self.srednji_ispusti_3 = QtGui.QRadioButton(self.groupBox_2)
        self.srednji_ispusti_3.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ispusti_3.setFont(font)
        self.srednji_ispusti_3.setObjectName(_fromUtf8("srednji_ispusti_3"))
        self.verticalLayout_10.addWidget(self.srednji_ispusti_3)
        self.srednji_ispusti_4 = QtGui.QRadioButton(self.groupBox_2)
        self.srednji_ispusti_4.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ispusti_4.setFont(font)
        self.srednji_ispusti_4.setObjectName(_fromUtf8("srednji_ispusti_4"))
        self.verticalLayout_10.addWidget(self.srednji_ispusti_4)
        self.srednji_ispusti_5 = QtGui.QRadioButton(self.groupBox_2)
        self.srednji_ispusti_5.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ispusti_5.setFont(font)
        self.srednji_ispusti_5.setObjectName(_fromUtf8("srednji_ispusti_5"))
        self.verticalLayout_10.addWidget(self.srednji_ispusti_5)
        self.srednji_ispusti_6 = QtGui.QRadioButton(self.groupBox_2)
        self.srednji_ispusti_6.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ispusti_6.setFont(font)
        self.srednji_ispusti_6.setObjectName(_fromUtf8("srednji_ispusti_6"))
        self.verticalLayout_10.addWidget(self.srednji_ispusti_6)
        self.srednji_dugme_zatvorisve = QtGui.QPushButton(self.groupBox_2)
        self.srednji_dugme_zatvorisve.setObjectName(_fromUtf8("srednji_dugme_zatvorisve"))
        self.verticalLayout_10.addWidget(self.srednji_dugme_zatvorisve)
        self.srednji_ispusti_6.raise_()
        self.srednji_ispusti_5.raise_()
        self.srednji_ispusti_4.raise_()
        self.srednji_ispusti_3.raise_()
        self.srednji_ispusti_2.raise_()
        self.srednji_ispusti_1.raise_()
        self.srednji_dugme_zatvorisve.raise_()
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.glavni)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.srednji_c20 = idQCheckBox(self.groupBox)
        self.srednji_c20.setMaximumSize(QtCore.QSize(16777215, 13))
        self.srednji_c20.setObjectName(_fromUtf8("srednji_c20"))
        self.verticalLayout_11.addWidget(self.srednji_c20)
        self.srednji_c24 = idQCheckBox(self.groupBox)
        self.srednji_c24.setMaximumSize(QtCore.QSize(16777215, 13))
        self.srednji_c24.setObjectName(_fromUtf8("srednji_c24"))
        self.verticalLayout_11.addWidget(self.srednji_c24)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.srednji.addLayout(self.verticalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.srednji.addItem(spacerItem6)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.srednji_ele1_1 = QtGui.QRadioButton(self.groupBox_4)
        self.srednji_ele1_1.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele1_1.setFont(font)
        self.srednji_ele1_1.setObjectName(_fromUtf8("srednji_ele1_1"))
        self.verticalLayout_12.addWidget(self.srednji_ele1_1)
        self.srednji_ele1_2 = QtGui.QRadioButton(self.groupBox_4)
        self.srednji_ele1_2.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele1_2.setFont(font)
        self.srednji_ele1_2.setObjectName(_fromUtf8("srednji_ele1_2"))
        self.verticalLayout_12.addWidget(self.srednji_ele1_2)
        self.srednji_ele1_3 = QtGui.QRadioButton(self.groupBox_4)
        self.srednji_ele1_3.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele1_3.setFont(font)
        self.srednji_ele1_3.setObjectName(_fromUtf8("srednji_ele1_3"))
        self.verticalLayout_12.addWidget(self.srednji_ele1_3)
        self.srednji_ele1_4 = QtGui.QRadioButton(self.groupBox_4)
        self.srednji_ele1_4.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_ele1_4.setFont(font)
        self.srednji_ele1_4.setObjectName(_fromUtf8("srednji_ele1_4"))
        self.verticalLayout_12.addWidget(self.srednji_ele1_4)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.srednji_23 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_23.setFont(font)
        self.srednji_23.setObjectName(_fromUtf8("srednji_23"))
        self.verticalLayout_6.addWidget(self.srednji_23)
        self.srednji_18 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_18.setFont(font)
        self.srednji_18.setObjectName(_fromUtf8("srednji_18"))
        self.verticalLayout_6.addWidget(self.srednji_18)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.srednji_21 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_21.setFont(font)
        self.srednji_21.setObjectName(_fromUtf8("srednji_21"))
        self.verticalLayout_6.addWidget(self.srednji_21)
        self.srednji_9 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_9.setFont(font)
        self.srednji_9.setObjectName(_fromUtf8("srednji_9"))
        self.verticalLayout_6.addWidget(self.srednji_9)
        self.srednji_c3 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_c3.setFont(font)
        self.srednji_c3.setObjectName(_fromUtf8("srednji_c3"))
        self.verticalLayout_6.addWidget(self.srednji_c3)
        self.srednji_c1 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_c1.setFont(font)
        self.srednji_c1.setObjectName(_fromUtf8("srednji_c1"))
        self.verticalLayout_6.addWidget(self.srednji_c1)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem9)
        self.srednji.addLayout(self.verticalLayout_6)
        spacerItem10 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.srednji.addItem(spacerItem10)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.srednji_psilosa_1 = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_psilosa_1.setFont(font)
        self.srednji_psilosa_1.setObjectName(_fromUtf8("srednji_psilosa_1"))
        self.verticalLayout_17.addWidget(self.srednji_psilosa_1)
        self.srednji_psilosa_2 = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_psilosa_2.setFont(font)
        self.srednji_psilosa_2.setObjectName(_fromUtf8("srednji_psilosa_2"))
        self.verticalLayout_17.addWidget(self.srednji_psilosa_2)
        self.srednji_psilosa_3 = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_psilosa_3.setFont(font)
        self.srednji_psilosa_3.setObjectName(_fromUtf8("srednji_psilosa_3"))
        self.verticalLayout_17.addWidget(self.srednji_psilosa_3)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.srednji_c5 = idQCheckBox(self.glavni)
        self.srednji_c5.setObjectName(_fromUtf8("srednji_c5"))
        self.verticalLayout_5.addWidget(self.srednji_c5)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.verticalLayout_36 = QtGui.QVBoxLayout()
        self.verticalLayout_36.setContentsMargins(40, 0, -1, 0)
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.label_3 = QtGui.QLabel(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_36.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.srednji_dugme_start = QtGui.QPushButton(self.glavni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_dugme_start.sizePolicy().hasHeightForWidth())
        self.srednji_dugme_start.setSizePolicy(sizePolicy)
        self.srednji_dugme_start.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.srednji_dugme_start.setFont(font)
        self.srednji_dugme_start.setObjectName(_fromUtf8("srednji_dugme_start"))
        self.horizontalLayout_4.addWidget(self.srednji_dugme_start)
        spacerItem12 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.srednji_dugme_stop = QtGui.QPushButton(self.glavni)
        self.srednji_dugme_stop.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.srednji_dugme_stop.setFont(font)
        self.srednji_dugme_stop.setObjectName(_fromUtf8("srednji_dugme_stop"))
        self.horizontalLayout_4.addWidget(self.srednji_dugme_stop)
        self.verticalLayout_36.addLayout(self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(self.glavni)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_36.addWidget(self.label_4)
        self.srednji_25 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_25.setFont(font)
        self.srednji_25.setObjectName(_fromUtf8("srednji_25"))
        self.verticalLayout_36.addWidget(self.srednji_25)
        self.verticalLayout_5.addLayout(self.verticalLayout_36)
        spacerItem13 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem13)
        self.srednji.addLayout(self.verticalLayout_5)
        spacerItem14 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.srednji.addItem(spacerItem14)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.srednji_bin1 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin1.sizePolicy().hasHeightForWidth())
        self.srednji_bin1.setSizePolicy(sizePolicy)
        self.srednji_bin1.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin1.setFont(font)
        self.srednji_bin1.setObjectName(_fromUtf8("srednji_bin1"))
        self.verticalLayout_34.addWidget(self.srednji_bin1)
        self.srednji_bin2 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin2.sizePolicy().hasHeightForWidth())
        self.srednji_bin2.setSizePolicy(sizePolicy)
        self.srednji_bin2.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin2.setFont(font)
        self.srednji_bin2.setObjectName(_fromUtf8("srednji_bin2"))
        self.verticalLayout_34.addWidget(self.srednji_bin2)
        self.srednji_bin3 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin3.sizePolicy().hasHeightForWidth())
        self.srednji_bin3.setSizePolicy(sizePolicy)
        self.srednji_bin3.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin3.setFont(font)
        self.srednji_bin3.setObjectName(_fromUtf8("srednji_bin3"))
        self.verticalLayout_34.addWidget(self.srednji_bin3)
        self.srednji_bin4 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin4.sizePolicy().hasHeightForWidth())
        self.srednji_bin4.setSizePolicy(sizePolicy)
        self.srednji_bin4.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin4.setFont(font)
        self.srednji_bin4.setObjectName(_fromUtf8("srednji_bin4"))
        self.verticalLayout_34.addWidget(self.srednji_bin4)
        self.srednji_bin5 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin5.sizePolicy().hasHeightForWidth())
        self.srednji_bin5.setSizePolicy(sizePolicy)
        self.srednji_bin5.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin5.setFont(font)
        self.srednji_bin5.setObjectName(_fromUtf8("srednji_bin5"))
        self.verticalLayout_34.addWidget(self.srednji_bin5)
        self.srednji_bin6 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin6.sizePolicy().hasHeightForWidth())
        self.srednji_bin6.setSizePolicy(sizePolicy)
        self.srednji_bin6.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin6.setFont(font)
        self.srednji_bin6.setObjectName(_fromUtf8("srednji_bin6"))
        self.verticalLayout_34.addWidget(self.srednji_bin6)
        self.srednji_bin7 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin7.sizePolicy().hasHeightForWidth())
        self.srednji_bin7.setSizePolicy(sizePolicy)
        self.srednji_bin7.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin7.setFont(font)
        self.srednji_bin7.setObjectName(_fromUtf8("srednji_bin7"))
        self.verticalLayout_34.addWidget(self.srednji_bin7)
        self.srednji_bin8 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin8.sizePolicy().hasHeightForWidth())
        self.srednji_bin8.setSizePolicy(sizePolicy)
        self.srednji_bin8.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin8.setFont(font)
        self.srednji_bin8.setObjectName(_fromUtf8("srednji_bin8"))
        self.verticalLayout_34.addWidget(self.srednji_bin8)
        self.srednji_bin9 = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srednji_bin9.sizePolicy().hasHeightForWidth())
        self.srednji_bin9.setSizePolicy(sizePolicy)
        self.srednji_bin9.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.srednji_bin9.setFont(font)
        self.srednji_bin9.setObjectName(_fromUtf8("srednji_bin9"))
        self.verticalLayout_34.addWidget(self.srednji_bin9)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.srednji_28 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_28.setFont(font)
        self.srednji_28.setObjectName(_fromUtf8("srednji_28"))
        self.verticalLayout_4.addWidget(self.srednji_28)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem15)
        self.srednji_31 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_31.setFont(font)
        self.srednji_31.setObjectName(_fromUtf8("srednji_31"))
        self.verticalLayout_4.addWidget(self.srednji_31)
        self.srednji_32 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_32.setFont(font)
        self.srednji_32.setObjectName(_fromUtf8("srednji_32"))
        self.verticalLayout_4.addWidget(self.srednji_32)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem16)
        self.srednji.addLayout(self.verticalLayout_4)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        spacerItem17 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_33.addItem(spacerItem17)
        self.srednji_dugme_ukljuci = QtGui.QPushButton(self.glavni)
        self.srednji_dugme_ukljuci.setObjectName(_fromUtf8("srednji_dugme_ukljuci"))
        self.verticalLayout_33.addWidget(self.srednji_dugme_ukljuci)
        self.srednji_dugme_iskljuci = QtGui.QPushButton(self.glavni)
        self.srednji_dugme_iskljuci.setObjectName(_fromUtf8("srednji_dugme_iskljuci"))
        self.verticalLayout_33.addWidget(self.srednji_dugme_iskljuci)
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.srednji_30 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_30.setFont(font)
        self.srednji_30.setObjectName(_fromUtf8("srednji_30"))
        self.verticalLayout_35.addWidget(self.srednji_30)
        self.label_5 = QtGui.QLabel(self.glavni)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_35.addWidget(self.label_5)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem18)
        self.srednji_19 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_19.setFont(font)
        self.srednji_19.setObjectName(_fromUtf8("srednji_19"))
        self.verticalLayout_35.addWidget(self.srednji_19)
        self.srednji_27 = idQCheckBox(self.glavni)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.srednji_27.setFont(font)
        self.srednji_27.setObjectName(_fromUtf8("srednji_27"))
        self.verticalLayout_35.addWidget(self.srednji_27)
        self.verticalLayout_33.addLayout(self.verticalLayout_35)
        spacerItem19 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_33.addItem(spacerItem19)
        self.srednji.addLayout(self.verticalLayout_33)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.srednji.addItem(spacerItem20)
        self.verticalLayout_2.addLayout(self.srednji)
        self.donji = QtGui.QHBoxLayout()
        self.donji.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.donji.setObjectName(_fromUtf8("donji"))
        self.widget_2 = QtGui.QWidget(self.glavni)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_2.setPalette(palette)
        self.widget_2.setAutoFillBackground(True)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.donji_p1 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p1.setFont(font)
        self.donji_p1.setObjectName(_fromUtf8("donji_p1"))
        self.verticalLayout_23.addWidget(self.donji_p1)
        self.donji_p1e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p1e.setFont(font)
        self.donji_p1e.setObjectName(_fromUtf8("donji_p1e"))
        self.verticalLayout_23.addWidget(self.donji_p1e)
        self.donji_p3 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p3.setFont(font)
        self.donji_p3.setObjectName(_fromUtf8("donji_p3"))
        self.verticalLayout_23.addWidget(self.donji_p3)
        self.donji_p3e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p3e.setFont(font)
        self.donji_p3e.setObjectName(_fromUtf8("donji_p3e"))
        self.verticalLayout_23.addWidget(self.donji_p3e)
        self.donji_p11 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p11.setFont(font)
        self.donji_p11.setObjectName(_fromUtf8("donji_p11"))
        self.verticalLayout_23.addWidget(self.donji_p11)
        self.donji_p11e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p11e.setFont(font)
        self.donji_p11e.setObjectName(_fromUtf8("donji_p11e"))
        self.verticalLayout_23.addWidget(self.donji_p11e)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem21)
        self.horizontalLayout_3.addLayout(self.verticalLayout_23)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.donji_p7 = idQCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p7.sizePolicy().hasHeightForWidth())
        self.donji_p7.setSizePolicy(sizePolicy)
        self.donji_p7.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p7.setFont(font)
        self.donji_p7.setIconSize(QtCore.QSize(16, 16))
        self.donji_p7.setObjectName(_fromUtf8("donji_p7"))
        self.verticalLayout_22.addWidget(self.donji_p7)
        self.donji_p7e = Led(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p7e.sizePolicy().hasHeightForWidth())
        self.donji_p7e.setSizePolicy(sizePolicy)
        self.donji_p7e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p7e.setFont(font)
        self.donji_p7e.setIconSize(QtCore.QSize(16, 16))
        self.donji_p7e.setObjectName(_fromUtf8("donji_p7e"))
        self.verticalLayout_22.addWidget(self.donji_p7e)
        self.donji_p8 = idQCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p8.sizePolicy().hasHeightForWidth())
        self.donji_p8.setSizePolicy(sizePolicy)
        self.donji_p8.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p8.setFont(font)
        self.donji_p8.setIconSize(QtCore.QSize(16, 16))
        self.donji_p8.setObjectName(_fromUtf8("donji_p8"))
        self.verticalLayout_22.addWidget(self.donji_p8)
        self.donji_p8e = Led(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p8e.sizePolicy().hasHeightForWidth())
        self.donji_p8e.setSizePolicy(sizePolicy)
        self.donji_p8e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p8e.setFont(font)
        self.donji_p8e.setIconSize(QtCore.QSize(16, 16))
        self.donji_p8e.setObjectName(_fromUtf8("donji_p8e"))
        self.verticalLayout_22.addWidget(self.donji_p8e)
        self.donji_p4 = idQCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p4.sizePolicy().hasHeightForWidth())
        self.donji_p4.setSizePolicy(sizePolicy)
        self.donji_p4.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p4.setFont(font)
        self.donji_p4.setIconSize(QtCore.QSize(16, 16))
        self.donji_p4.setObjectName(_fromUtf8("donji_p4"))
        self.verticalLayout_22.addWidget(self.donji_p4)
        self.donji_p4e = Led(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p4e.sizePolicy().hasHeightForWidth())
        self.donji_p4e.setSizePolicy(sizePolicy)
        self.donji_p4e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p4e.setFont(font)
        self.donji_p4e.setIconSize(QtCore.QSize(16, 16))
        self.donji_p4e.setObjectName(_fromUtf8("donji_p4e"))
        self.verticalLayout_22.addWidget(self.donji_p4e)
        self.donji_p2 = idQCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p2.sizePolicy().hasHeightForWidth())
        self.donji_p2.setSizePolicy(sizePolicy)
        self.donji_p2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p2.setFont(font)
        self.donji_p2.setIconSize(QtCore.QSize(16, 16))
        self.donji_p2.setObjectName(_fromUtf8("donji_p2"))
        self.verticalLayout_22.addWidget(self.donji_p2)
        self.donji_p2e = Led(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p2e.sizePolicy().hasHeightForWidth())
        self.donji_p2e.setSizePolicy(sizePolicy)
        self.donji_p2e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p2e.setFont(font)
        self.donji_p2e.setIconSize(QtCore.QSize(16, 16))
        self.donji_p2e.setObjectName(_fromUtf8("donji_p2e"))
        self.verticalLayout_22.addWidget(self.donji_p2e)
        self.donji_p5 = idQCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p5.sizePolicy().hasHeightForWidth())
        self.donji_p5.setSizePolicy(sizePolicy)
        self.donji_p5.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p5.setFont(font)
        self.donji_p5.setIconSize(QtCore.QSize(16, 16))
        self.donji_p5.setObjectName(_fromUtf8("donji_p5"))
        self.verticalLayout_22.addWidget(self.donji_p5)
        self.donji_p5e = Led(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p5e.sizePolicy().hasHeightForWidth())
        self.donji_p5e.setSizePolicy(sizePolicy)
        self.donji_p5e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p5e.setFont(font)
        self.donji_p5e.setIconSize(QtCore.QSize(16, 16))
        self.donji_p5e.setObjectName(_fromUtf8("donji_p5e"))
        self.verticalLayout_22.addWidget(self.donji_p5e)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem22)
        self.horizontalLayout_3.addLayout(self.verticalLayout_22)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.donji_p14 = idQCheckBox(self.widget_2)
        self.donji_p14.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p14.setFont(font)
        self.donji_p14.setObjectName(_fromUtf8("donji_p14"))
        self.verticalLayout_21.addWidget(self.donji_p14)
        self.donji_p14e = Led(self.widget_2)
        self.donji_p14e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p14e.setFont(font)
        self.donji_p14e.setObjectName(_fromUtf8("donji_p14e"))
        self.verticalLayout_21.addWidget(self.donji_p14e)
        self.donji_p15 = idQCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donji_p15.sizePolicy().hasHeightForWidth())
        self.donji_p15.setSizePolicy(sizePolicy)
        self.donji_p15.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p15.setFont(font)
        self.donji_p15.setObjectName(_fromUtf8("donji_p15"))
        self.verticalLayout_21.addWidget(self.donji_p15)
        self.donji_p15e = Led(self.widget_2)
        self.donji_p15e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p15e.setFont(font)
        self.donji_p15e.setObjectName(_fromUtf8("donji_p15e"))
        self.verticalLayout_21.addWidget(self.donji_p15e)
        self.donji_p16 = idQCheckBox(self.widget_2)
        self.donji_p16.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p16.setFont(font)
        self.donji_p16.setObjectName(_fromUtf8("donji_p16"))
        self.verticalLayout_21.addWidget(self.donji_p16)
        self.donji_p16e = Led(self.widget_2)
        self.donji_p16e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p16e.setFont(font)
        self.donji_p16e.setObjectName(_fromUtf8("donji_p16e"))
        self.verticalLayout_21.addWidget(self.donji_p16e)
        self.donji_p12 = idQCheckBox(self.widget_2)
        self.donji_p12.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p12.setFont(font)
        self.donji_p12.setObjectName(_fromUtf8("donji_p12"))
        self.verticalLayout_21.addWidget(self.donji_p12)
        self.donji_p12e = Led(self.widget_2)
        self.donji_p12e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p12e.setFont(font)
        self.donji_p12e.setObjectName(_fromUtf8("donji_p12e"))
        self.verticalLayout_21.addWidget(self.donji_p12e)
        self.donji_p13 = idQCheckBox(self.widget_2)
        self.donji_p13.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p13.setFont(font)
        self.donji_p13.setObjectName(_fromUtf8("donji_p13"))
        self.verticalLayout_21.addWidget(self.donji_p13)
        self.donji_p13e = Led(self.widget_2)
        self.donji_p13e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p13e.setFont(font)
        self.donji_p13e.setObjectName(_fromUtf8("donji_p13e"))
        self.verticalLayout_21.addWidget(self.donji_p13e)
        self.donji_p6 = idQCheckBox(self.widget_2)
        self.donji_p6.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p6.setFont(font)
        self.donji_p6.setObjectName(_fromUtf8("donji_p6"))
        self.verticalLayout_21.addWidget(self.donji_p6)
        self.donji_p6e = Led(self.widget_2)
        self.donji_p6e.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p6e.setFont(font)
        self.donji_p6e.setObjectName(_fromUtf8("donji_p6e"))
        self.verticalLayout_21.addWidget(self.donji_p6e)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_21)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.donji_p25 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p25.setFont(font)
        self.donji_p25.setObjectName(_fromUtf8("donji_p25"))
        self.verticalLayout_20.addWidget(self.donji_p25)
        self.donji_p25e = Led(self.widget_2)
        self.donji_p25e.setText(_fromUtf8(""))
        self.donji_p25e.setObjectName(_fromUtf8("donji_p25e"))
        self.verticalLayout_20.addWidget(self.donji_p25e)
        self.donji_s2 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_s2.setFont(font)
        self.donji_s2.setObjectName(_fromUtf8("donji_s2"))
        self.verticalLayout_20.addWidget(self.donji_s2)
        self.donji_s2e = Led(self.widget_2)
        self.donji_s2e.setText(_fromUtf8(""))
        self.donji_s2e.setObjectName(_fromUtf8("donji_s2e"))
        self.verticalLayout_20.addWidget(self.donji_s2e)
        self.donji_s1 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_s1.setFont(font)
        self.donji_s1.setObjectName(_fromUtf8("donji_s1"))
        self.verticalLayout_20.addWidget(self.donji_s1)
        self.donji_s1e = Led(self.widget_2)
        self.donji_s1e.setText(_fromUtf8(""))
        self.donji_s1e.setObjectName(_fromUtf8("donji_s1e"))
        self.verticalLayout_20.addWidget(self.donji_s1e)
        self.donji_p17 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p17.setFont(font)
        self.donji_p17.setObjectName(_fromUtf8("donji_p17"))
        self.verticalLayout_20.addWidget(self.donji_p17)
        self.donji_p17e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p17e.setFont(font)
        self.donji_p17e.setObjectName(_fromUtf8("donji_p17e"))
        self.verticalLayout_20.addWidget(self.donji_p17e)
        self.donji_p32 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p32.setFont(font)
        self.donji_p32.setObjectName(_fromUtf8("donji_p32"))
        self.verticalLayout_20.addWidget(self.donji_p32)
        self.donji_p32e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p32e.setFont(font)
        self.donji_p32e.setObjectName(_fromUtf8("donji_p32e"))
        self.verticalLayout_20.addWidget(self.donji_p32e)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem24)
        self.horizontalLayout_3.addLayout(self.verticalLayout_20)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.donji_p27 = idQCheckBox(self.widget_2)
        self.donji_p27.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p27.setFont(font)
        self.donji_p27.setObjectName(_fromUtf8("donji_p27"))
        self.verticalLayout_29.addWidget(self.donji_p27)
        self.donji_p27e = Led(self.widget_2)
        self.donji_p27e.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p27e.setFont(font)
        self.donji_p27e.setObjectName(_fromUtf8("donji_p27e"))
        self.verticalLayout_29.addWidget(self.donji_p27e)
        self.donji_p28 = idQCheckBox(self.widget_2)
        self.donji_p28.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p28.setFont(font)
        self.donji_p28.setObjectName(_fromUtf8("donji_p28"))
        self.verticalLayout_29.addWidget(self.donji_p28)
        self.donji_p28e = Led(self.widget_2)
        self.donji_p28e.setMaximumSize(QtCore.QSize(16777215, 18))
        self.donji_p28e.setText(_fromUtf8(""))
        self.donji_p28e.setObjectName(_fromUtf8("donji_p28e"))
        self.verticalLayout_29.addWidget(self.donji_p28e)
        self.donji_p10 = idQCheckBox(self.widget_2)
        self.donji_p10.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p10.setFont(font)
        self.donji_p10.setObjectName(_fromUtf8("donji_p10"))
        self.verticalLayout_29.addWidget(self.donji_p10)
        self.donji_p10e = Led(self.widget_2)
        self.donji_p10e.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p10e.setFont(font)
        self.donji_p10e.setObjectName(_fromUtf8("donji_p10e"))
        self.verticalLayout_29.addWidget(self.donji_p10e)
        self.donji_p20 = idQCheckBox(self.widget_2)
        self.donji_p20.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p20.setFont(font)
        self.donji_p20.setObjectName(_fromUtf8("donji_p20"))
        self.verticalLayout_29.addWidget(self.donji_p20)
        self.donji_p20e = Led(self.widget_2)
        self.donji_p20e.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p20e.setFont(font)
        self.donji_p20e.setObjectName(_fromUtf8("donji_p20e"))
        self.verticalLayout_29.addWidget(self.donji_p20e)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem25)
        self.horizontalLayout_3.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.donji_p18 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p18.setFont(font)
        self.donji_p18.setObjectName(_fromUtf8("donji_p18"))
        self.verticalLayout_30.addWidget(self.donji_p18)
        self.donji_p18e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p18e.setFont(font)
        self.donji_p18e.setObjectName(_fromUtf8("donji_p18e"))
        self.verticalLayout_30.addWidget(self.donji_p18e)
        self.donji_gotovpera = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_gotovpera.setFont(font)
        self.donji_gotovpera.setObjectName(_fromUtf8("donji_gotovpera"))
        self.verticalLayout_30.addWidget(self.donji_gotovpera)
        self.donji_gotovmat = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_gotovmat.setFont(font)
        self.donji_gotovmat.setObjectName(_fromUtf8("donji_gotovmat"))
        self.verticalLayout_30.addWidget(self.donji_gotovmat)
        self.donji_p19 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p19.setFont(font)
        self.donji_p19.setObjectName(_fromUtf8("donji_p19"))
        self.verticalLayout_30.addWidget(self.donji_p19)
        self.donji_p19e = Led(self.widget_2)
        self.donji_p19e.setText(_fromUtf8(""))
        self.donji_p19e.setObjectName(_fromUtf8("donji_p19e"))
        self.verticalLayout_30.addWidget(self.donji_p19e)
        self.donji_p31 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p31.setFont(font)
        self.donji_p31.setObjectName(_fromUtf8("donji_p31"))
        self.verticalLayout_30.addWidget(self.donji_p31)
        self.donji_p31e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p31e.setFont(font)
        self.donji_p31e.setObjectName(_fromUtf8("donji_p31e"))
        self.verticalLayout_30.addWidget(self.donji_p31e)
        self.donji_p30 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p30.setFont(font)
        self.donji_p30.setObjectName(_fromUtf8("donji_p30"))
        self.verticalLayout_30.addWidget(self.donji_p30)
        self.donji_p30e = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p30e.setFont(font)
        self.donji_p30e.setObjectName(_fromUtf8("donji_p30e"))
        self.verticalLayout_30.addWidget(self.donji_p30e)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem26)
        self.horizontalLayout_3.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.donji_gotmat3 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_gotmat3.setFont(font)
        self.donji_gotmat3.setObjectName(_fromUtf8("donji_gotmat3"))
        self.verticalLayout_31.addWidget(self.donji_gotmat3)
        self.donji_puz24 = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_puz24.setFont(font)
        self.donji_puz24.setObjectName(_fromUtf8("donji_puz24"))
        self.verticalLayout_31.addWidget(self.donji_puz24)
        spacerItem27 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_31.addItem(spacerItem27)
        self.donji_p26 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_p26.setFont(font)
        self.donji_p26.setObjectName(_fromUtf8("donji_p26"))
        self.verticalLayout_31.addWidget(self.donji_p26)
        self.donji_p26e = Led(self.widget_2)
        self.donji_p26e.setText(_fromUtf8(""))
        self.donji_p26e.setObjectName(_fromUtf8("donji_p26e"))
        self.verticalLayout_31.addWidget(self.donji_p26e)
        spacerItem28 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_31.addItem(spacerItem28)
        self.donji_b29 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_b29.setFont(font)
        self.donji_b29.setObjectName(_fromUtf8("donji_b29"))
        self.verticalLayout_31.addWidget(self.donji_b29)
        self.donji_puz29 = Led(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_puz29.setFont(font)
        self.donji_puz29.setObjectName(_fromUtf8("donji_puz29"))
        self.verticalLayout_31.addWidget(self.donji_puz29)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem29)
        self.horizontalLayout_3.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.donji_gotmat4 = idQCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.donji_gotmat4.setFont(font)
        self.donji_gotmat4.setObjectName(_fromUtf8("donji_gotmat4"))
        self.verticalLayout_32.addWidget(self.donji_gotmat4)
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem30)
        self.horizontalLayout_3.addLayout(self.verticalLayout_32)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem31)
        self.donji.addWidget(self.widget_2)
        self.verticalLayout_2.addLayout(self.donji)
        MainWindow.setCentralWidget(self.glavni)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPregledi_i_izvestaji = QtGui.QMenu(self.menubar)
        self.menuPregledi_i_izvestaji.setObjectName(_fromUtf8("menuPregledi_i_izvestaji"))
        self.menuUnos_i_promena_podataka = QtGui.QMenu(self.menubar)
        self.menuUnos_i_promena_podataka.setObjectName(_fromUtf8("menuUnos_i_promena_podataka"))
        self.menuUtovar = QtGui.QMenu(self.menubar)
        self.menuUtovar.setObjectName(_fromUtf8("menuUtovar"))
        self.menuPretovar = QtGui.QMenu(self.menubar)
        self.menuPretovar.setObjectName(_fromUtf8("menuPretovar"))
        self.menuProzori = QtGui.QMenu(self.menubar)
        self.menuProzori.setObjectName(_fromUtf8("menuProzori"))
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuPregledi_i_izvestaji.menuAction())
        self.menubar.addAction(self.menuUnos_i_promena_podataka.menuAction())
        self.menubar.addAction(self.menuUtovar.menuAction())
        self.menubar.addAction(self.menuPretovar.menuAction())
        self.menubar.addAction(self.menuProzori.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BIOVITA", None))
        self.gornji_bin1.setText(_translate("MainWindow", "BIN1", None))
        self.gornji_bin2.setText(_translate("MainWindow", "BIN2", None))
        self.gornji_bin3.setText(_translate("MainWindow", "BIN3", None))
        self.gornji_bin4.setText(_translate("MainWindow", "BIN4", None))
        self.gornji_bin5.setText(_translate("MainWindow", "BIN5", None))
        self.gornji_bin6.setText(_translate("MainWindow", "BIN6", None))
        self.gornji_bin7.setText(_translate("MainWindow", "BIN7", None))
        self.gornji_bin8.setText(_translate("MainWindow", "BIN8", None))
        self.gornji_bin9.setText(_translate("MainWindow", "BIN9", None))
        self.gornji_bin12.setText(_translate("MainWindow", "BIN12 premixi na vagu", None))
        self.gornji_c15.setText(_translate("MainWindow", "c15 elevator mlina", None))
        self.gornji_c29.setText(_translate("MainWindow", "c29 dotok materijala u mlin", None))
        self.label.setText(_translate("MainWindow", "Mesaona KLAPNA gore", None))
        self.gornji_22.setText(_translate("MainWindow", "22 OTVORENA", None))
        self.gornji_26.setText(_translate("MainWindow", "26 ZATVORENA", None))
        self.label_2.setText(_translate("MainWindow", "Mesaona KLAPNA dole", None))
        self.gornji_17.setText(_translate("MainWindow", "17 ZATVORENA", None))
        self.gornji_16.setText(_translate("MainWindow", "16 OTVORENA", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "ELEVATOR 2", None))
        self.srednji_ele2_1.setText(_translate("MainWindow", "SILOS 4", None))
        self.srednji_ele2_2.setText(_translate("MainWindow", "SILOS 5", None))
        self.srednji_ele2_3.setText(_translate("MainWindow", "ZA EKSTRUDER", None))
        self.srednji_ele2_4.setText(_translate("MainWindow", "UTOVAR BINOVA ZA VAGU", None))
        self.srednji_ele2_5.setText(_translate("MainWindow", "ASPIRATER", None))
        self.srednji_ele2_6.setText(_translate("MainWindow", "REDLER IZNAD SILOSA", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "ISPUSTI SILOSA", None))
        self.srednji_ispusti_1.setText(_translate("MainWindow", "SILOS 1", None))
        self.srednji_ispusti_2.setText(_translate("MainWindow", "SILOS 2", None))
        self.srednji_ispusti_3.setText(_translate("MainWindow", "SILOS 3", None))
        self.srednji_ispusti_4.setText(_translate("MainWindow", "SILOS 4", None))
        self.srednji_ispusti_5.setText(_translate("MainWindow", "SILOS 5", None))
        self.srednji_ispusti_6.setText(_translate("MainWindow", "SILOS 6", None))
        self.srednji_dugme_zatvorisve.setText(_translate("MainWindow", "Zatvori sve", None))
        self.groupBox.setTitle(_translate("MainWindow", "TUNELI", None))
        self.srednji_c20.setText(_translate("MainWindow", "C20 TRAKA 2", None))
        self.srednji_c24.setText(_translate("MainWindow", "c24 TRAKA 1", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "ELEVATOR 1", None))
        self.srednji_ele1_1.setText(_translate("MainWindow", "REDLER IZNAD SILOSA", None))
        self.srednji_ele1_2.setText(_translate("MainWindow", "ASPIRATER", None))
        self.srednji_ele1_3.setText(_translate("MainWindow", "UTOVARNA RAMPA", None))
        self.srednji_ele1_4.setText(_translate("MainWindow", "UTOVAR BINOVA ZA VAGU", None))
        self.srednji_23.setText(_translate("MainWindow", "23 ELEVATOR 1", None))
        self.srednji_18.setText(_translate("MainWindow", "18 ELEVATOR 2", None))
        self.srednji_21.setText(_translate("MainWindow", "21 VENTILATOR ASPIRATERA", None))
        self.srednji_9.setText(_translate("MainWindow", "9 ASPIRATER PRECISTAC", None))
        self.srednji_c3.setText(_translate("MainWindow", "C3 PUZ U ISTOVARNOJ JAMI", None))
        self.srednji_c1.setText(_translate("MainWindow", "C1 REDLER U ISTOVARNOJ JAMI", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "PUNJENJE SILOSA REDLER", None))
        self.srednji_psilosa_1.setText(_translate("MainWindow", "SILOS 1", None))
        self.srednji_psilosa_2.setText(_translate("MainWindow", "SILOS 2", None))
        self.srednji_psilosa_3.setText(_translate("MainWindow", "SILOS 3", None))
        self.srednji_c5.setText(_translate("MainWindow", "c5 REDLER IZNAD SILOSA", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">GOTOVA ROBA IZ MESALICE</p></body></html>", None))
        self.srednji_dugme_start.setText(_translate("MainWindow", "START", None))
        self.srednji_dugme_stop.setText(_translate("MainWindow", "STOP", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PUZ OD MESAONE </p><p align=\"center\">KA ELEVATORU 3</p></body></html>", None))
        self.srednji_25.setText(_translate("MainWindow", "25 ELEVATOR 3", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "PUNJENJE BINOVA", None))
        self.srednji_bin1.setText(_translate("MainWindow", "BIN 1", None))
        self.srednji_bin2.setText(_translate("MainWindow", "BIN 2", None))
        self.srednji_bin3.setText(_translate("MainWindow", "BIN 3", None))
        self.srednji_bin4.setText(_translate("MainWindow", "BIN 4", None))
        self.srednji_bin5.setText(_translate("MainWindow", "BIN 5", None))
        self.srednji_bin6.setText(_translate("MainWindow", "BIN 6", None))
        self.srednji_bin7.setText(_translate("MainWindow", "BIN 7", None))
        self.srednji_bin8.setText(_translate("MainWindow", "BIN 8", None))
        self.srednji_bin9.setText(_translate("MainWindow", "BIN 9", None))
        self.srednji_28.setText(_translate("MainWindow", "28 GOTOVA ROBA \n"
"PREMA EXTRUDERU", None))
        self.srednji_31.setText(_translate("MainWindow", "31 mesalica", None))
        self.srednji_32.setText(_translate("MainWindow", "32 mlin", None))
        self.srednji_dugme_ukljuci.setText(_translate("MainWindow", "UKLJUCI", None))
        self.srednji_dugme_iskljuci.setText(_translate("MainWindow", "ISKLJUCI", None))
        self.srednji_30.setText(_translate("MainWindow", "30 PUZ ZA PUNJENJE BINOVA", None))
        self.label_5.setText(_translate("MainWindow", "(iznad binova)", None))
        self.srednji_19.setText(_translate("MainWindow", "19 PUZ I PNEUMATIKA ZA 8/9", None))
        self.srednji_27.setText(_translate("MainWindow", "27 REZERVA", None))
        self.donji_p1.setText(_translate("MainWindow", "P1", None))
        self.donji_p1e.setText(_translate("MainWindow", "E1 Aspirater/Puz binova", None))
        self.donji_p3.setText(_translate("MainWindow", "P3", None))
        self.donji_p3e.setText(_translate("MainWindow", "E1 Zatvor/Rampa", None))
        self.donji_p11.setText(_translate("MainWindow", "P11", None))
        self.donji_p11e.setText(_translate("MainWindow", "Red. Iznad silosa zatvo.", None))
        self.donji_p7.setText(_translate("MainWindow", "P7", None))
        self.donji_p7e.setText(_translate("MainWindow", "E2 Zatv/S5", None))
        self.donji_p8.setText(_translate("MainWindow", "P8", None))
        self.donji_p8e.setText(_translate("MainWindow", "E2 zatv/kod Pere", None))
        self.donji_p4.setText(_translate("MainWindow", "P4", None))
        self.donji_p4e.setText(_translate("MainWindow", "E2 Zatv/ Puz za bin", None))
        self.donji_p2.setText(_translate("MainWindow", "P2", None))
        self.donji_p2e.setText(_translate("MainWindow", "E2 Regl/aspirater", None))
        self.donji_p5.setText(_translate("MainWindow", "P5", None))
        self.donji_p5e.setText(_translate("MainWindow", "E2 Zatv/silos 4", None))
        self.donji_p14.setText(_translate("MainWindow", "P14", None))
        self.donji_p14e.setText(_translate("MainWindow", "Silos 1 ispust otvo", None))
        self.donji_p15.setText(_translate("MainWindow", "P15", None))
        self.donji_p15e.setText(_translate("MainWindow", "Silos 2 ispust otvo", None))
        self.donji_p16.setText(_translate("MainWindow", "P16", None))
        self.donji_p16e.setText(_translate("MainWindow", "Silos 3 ispust otvo", None))
        self.donji_p12.setText(_translate("MainWindow", "P12", None))
        self.donji_p12e.setText(_translate("MainWindow", "Silos 4 ispust otvo", None))
        self.donji_p13.setText(_translate("MainWindow", "P13", None))
        self.donji_p13e.setText(_translate("MainWindow", "Silos 5 ispust otvo", None))
        self.donji_p6.setText(_translate("MainWindow", "P6", None))
        self.donji_p6e.setText(_translate("MainWindow", "Silos 6 ispu. otvoren", None))
        self.donji_p25.setText(_translate("MainWindow", "P25 Silos 3 zasun", None))
        self.donji_s2.setText(_translate("MainWindow", "Silos 2 zasun", None))
        self.donji_s1.setText(_translate("MainWindow", "Silos 1 zasun", None))
        self.donji_p17.setText(_translate("MainWindow", "P17", None))
        self.donji_p17e.setText(_translate("MainWindow", "ISPUST REGL 1/6", None))
        self.donji_p32.setText(_translate("MainWindow", "P32", None))
        self.donji_p32e.setText(_translate("MainWindow", "USMERIVAC 1/6", None))
        self.donji_p27.setText(_translate("MainWindow", "P27", None))
        self.donji_p27e.setText(_translate("MainWindow", "PREMIX", None))
        self.donji_p28.setText(_translate("MainWindow", "P28 VAGA", None))
        self.donji_p10.setText(_translate("MainWindow", "P10", None))
        self.donji_p10e.setText(_translate("MainWindow", "Ispust REGL. 2/5", None))
        self.donji_p20.setText(_translate("MainWindow", "P20", None))
        self.donji_p20e.setText(_translate("MainWindow", "USMERIVAC 2/5", None))
        self.donji_p18.setText(_translate("MainWindow", "P18", None))
        self.donji_p18e.setText(_translate("MainWindow", "GOT MAT2/ZATV/OTV", None))
        self.donji_gotovpera.setText(_translate("MainWindow", "gotovPera 2/1", None))
        self.donji_gotovmat.setText(_translate("MainWindow", "Gotov mat/1 otvoreno/yat", None))
        self.donji_p19.setText(_translate("MainWindow", "P19", None))
        self.donji_p31.setText(_translate("MainWindow", "P31", None))
        self.donji_p31e.setText(_translate("MainWindow", "ISPUST REGL 3/4", None))
        self.donji_p30.setText(_translate("MainWindow", "P30", None))
        self.donji_p30e.setText(_translate("MainWindow", "USMERIVAC 3/4", None))
        self.donji_gotmat3.setText(_translate("MainWindow", "got_mat3  zasun/zat", None))
        self.donji_puz24.setText(_translate("MainWindow", "puz 24", None))
        self.donji_p26.setText(_translate("MainWindow", "P26 got_mat4 zasun", None))
        self.donji_b29.setText(_translate("MainWindow", "b29 klapna 8/9 bin", None))
        self.donji_puz29.setText(_translate("MainWindow", "puz29", None))
        self.donji_gotmat4.setText(_translate("MainWindow", "got_mat4", None))
        self.menuPregledi_i_izvestaji.setTitle(_translate("MainWindow", "Pregledi i izvestaji", None))
        self.menuUnos_i_promena_podataka.setTitle(_translate("MainWindow", "Unos i promena podataka", None))
        self.menuUtovar.setTitle(_translate("MainWindow", "Utovar", None))
        self.menuPretovar.setTitle(_translate("MainWindow", "Pretovar", None))
        self.menuProzori.setTitle(_translate("MainWindow", "Prozori", None))

from idcheckbox import idQCheckBox
from led import Led
